### ISSUE TITLE
App spec failures due to missing `current_user` method

### ISSUE THREAD

**Issue by samstokes** [honeycombio/honeycomb-rails#10]
Reports of end-user spec failures (presumably when doing integration testing on an app with HoneycombRails installed) due to `honeycomb_user_metadata_devise` calling `current_user` on a controller instance that doesn't have that method.

We've already added a [workaround](https://github.com/honeycombio/honeycomb-rails/commit/2493dc3fb4b1322390528a74ac46199d84d3adab), but the fact that was even needed suggests a bug or wrong assumption somewhere.

`honeycomb_user_metadata_devise` is called from `honeycomb_user_metadata`, whose behaviour is controlled by [`Config#record_user`](http://www.rubydoc.info/gems/honeycomb-rails/HoneycombRails/Config#record_user-instance_method). The `_devise` variant is only called if `record_user = :devise`, which only happens if it was explicitly configured, or if it was previously set to `:detect` (the default) and we detected a `current_user` method. So in other words, assuming this wasn't just a misconfiguration, for this issue to occur means we *already* checked for `current_user` and then later on it wasn't there.

A plausible scenario would be if *some* controllers in the application define `current_user` and some don't. In that case, we don't do the right thing for either explicit configuration (`:devise`) or autodetection (`:detect`). For `record_user = :devise`, we'll just fail on the controllers without `current_user`. For `record_user = :detect`, the behaviour will depend on which controller is encountered first in the lifetime of the process (whether at app runtime or during a test suite run).

Some pondering needed for the right solution. Doing a `respond_to?` check for every request isn't super efficient and doesn't feel clean either - maybe memoise it per controller class?

Anyway, to @christineyen to confirm whether any details of the "plausible scenario" above match the reported situation, then feel free to punt it back for pondering :)

**Comment by christineyen** [comment]
Mm, I like the idea of memoizing per controller class. Marcus said it was failing sporadically, though idk if that meant "for some specs" or "nondeterministically." I'll get back to you as I hear more.

**Comment by christineyen** [comment]
Adding some more metadata for future investigation:

- Rails 4.2.8
- "when we turned off `report_user` by setting it to `false`, all the specs failed" -> ??
- An engineer also suspected ^ **some** controllers using `devise` and some not. Seemed like a plausible and reasonable situation for their codebase to be in.

Un-assigning this from me for pondering :)
