### ISSUE TITLE
Thorny initialization issue around initialization of `honeycomb_metadata`

### ISSUE THREAD

**Issue by christineyen** [honeycombio/honeycomb-rails#17]
Per the knee-jerk fix in #16 to Issue https://github.com/honeycombio/honeycomb-rails/issues/12, looks like we have run into the thorny initialization issues suggested in the PR description (a justification for the pre-#16 state).

We should look into this and capture the initialization behavior in a test so future me's don't go stumbling around undoing things that were done for a perfectly good reason.

For symptoms, see Issue https://github.com/honeycombio/honeycomb-rails/issues/12 on one hand and this on the other (after @cyrus-one updated to version 0.4.1):
![screen shot 2018-01-25 at 01 51 01](https://user-images.githubusercontent.com/188595/35386004-39feab5c-017f-11e8-9b33-761bf7d11469.png)

**Comment by samstokes** [comment]
This is hard to test with a unit test, because it depends on the actual behaviour of Rails. I'd chalk this one down as a case to test under #1.
