### ISSUE TITLE
Do not always display the "No writekey defined!" warning

### ISSUE THREAD

**Issue by renchap** [honeycombio/honeycomb-rails#23]
When no `writekey` is defined, `honeycomb-rails` prints a message on `stdout` on each startup (including running tests, rake tasks like `assets:precompile` when deploying, …):

```
» rails test
No writekey defined! (Check your config's `writekey` value in config/initializers/honeycomb.rb) No events will be sent to Honeycomb.

# Running tests with run options --seed 11499:
```

My current initializer:
```ruby
# config/initializers/honeycomb.rb
if ENV["HONEYCOMB_WRITEKEY"]
  HoneycombRails.configure do |conf|
    conf.writekey = ENV["HONEYCOMB_WRITEKEY"]
    # ...
  end
end
```

This is great for onboarding and new users but a bit annoying otherwise. I personally would like to be able to completely disable `honeycomb-rails` except if it is configured. Maybe something like:

```ruby
# config/initializers/honeycomb.rb
HoneycombRails.configure do |conf|
   conf.enabled = !!ENV["HONEYCOMB_WRITEKEY"]
end
```

The message could be displayed if `HoneycombRails.configure` has not been called at all, but not displayed if it has been explicitely disabled. I am not sure it will work with rake tasks, but might be worth a try.

**Comment by renchap** [comment]
Probably related to #25

**Comment by emfree** [comment]
Hi @renchap, thanks for writing in. I can definitely see how that would get noisy. It looks like you might be able to silence the warning by explicitly configuring a null client: 

```
HoneycombRails.configure do |conf|
   conf.client = Libhoney::NullClient.new
end
```
However I'm not the `honeycomb-rails` expert so I'm not quite certain.

**Comment by martin308** [comment]
@renchap we are moving further development effort over to [beeline-ruby](https://github.com/honeycombio/beeline-ruby), log output is more configurable in that gem. Let us know if you have the same issue over there, thanks!
