### ISSUE TITLE
gem expects `current_user` to respond to `admin?`

### ISSUE THREAD

**Issue by trevvvy** [honeycombio/honeycomb-rails#32]
We don't use devise, but the `honeycomb_user_metadata_devise` method is expecting our `current_user` object to respond to `admin?`, which is not a notion in our app. Seems like this is a very proprietary expectation to have in this gem.  Maybe this behaviour should be opt in for apps that are using devise?

**Comment by martin308** [comment]
@trevvvy we have just completed a lot of additions to the [honeycomb-beeline](https://github.com/honeycombio/beeline-ruby) gem and are intending it to succeed this project. Shout out over there if you have any difficulties getting up and running with it
